version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mpslytherin?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./src:/app/src  # Monta el código fuente desde tu máquina local al contenedor
    networks:
      - springboot-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mpslytherin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge